# Generated by Django 3.0.2 on 2020-02-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=2000)),
                ('desc', models.TextField()),
                ('duration', models.CharField(choices=[('2 to 4 Weeks', '1'), ('4 to 6 Weeks', '2'), ('6 to 8 Weeks', 3)], default='2 to 4 Weeks', max_length=50)),
            ],
        ),
    ]
