# Generated by Django 3.0.2 on 2020-03-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubmission',
            name='duration',
            field=models.CharField(choices=[('1', '2 to 4 Weeks'), ('2', '4 to 6 Weeks'), ('3', '6 to 8 Weeks')], default='2 to 4 Weeks', max_length=50),
        ),
    ]
