# Generated by Django 3.0.2 on 2020-03-15 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200311_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='banner_img',
        ),
    ]
