# Generated by Django 3.0.2 on 2020-02-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200208_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='desc',
            field=models.CharField(default='desc', max_length=1000),
            preserve_default=False,
        ),
    ]
