# Generated by Django 3.0.2 on 2020-03-16 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
