# Generated by Django 3.0.2 on 2020-02-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200205_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='faculty',
        ),
    ]
