# Generated by Django 3.0.2 on 2020-02-05 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_level_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='faculty',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Faculty'),
            preserve_default=False,
        ),
    ]
