# Generated by Django 3.0.2 on 2020-02-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200206_0140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'universities'},
        ),
        migrations.AddField(
            model_name='material',
            name='course_code',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
