# Generated by Django 3.0.2 on 2020-02-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_material_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='review',
        ),
    ]
