# Generated by Django 3.0.2 on 2020-02-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200208_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='desc',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
