# Generated by Django 3.0.2 on 2020-02-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200208_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.ImageField(default='', upload_to='school_logo/'),
            preserve_default=False,
        ),
    ]
