# Generated by Django 3.0.2 on 2020-03-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_university_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(default='/', upload_to='course_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='file_path',
            field=models.FileField(upload_to=''),
        ),
    ]
