# Generated by Django 3.0.2 on 2020-03-16 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_subscribe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribe',
            new_name='Subscriber',
        ),
    ]
